'use strict';

export const INITIAL_CONVERSATION_LIST = 'INITIAL_CONVERSATION_LIST';
export const LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const ADDING_FRIEND = 'ADDING_FRIEND';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_ERROR = 'ADD_FRIEND_ERROR';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const LOAD_ERROR = 'LOAD_ERROR';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';

export const BEFORE_UPDATE_INFO = 'BEFORE_UPDATE_INFO';
export const AFTER_UPDATE_INFO = 'AFTER_UPDATE_INFO';
export const INITIAL_MESSAGE_LIST = 'INITIAL_MESSAGE_LIST';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';