'use strict';

export const INITIAL_CONVERSATION_LIST = 'INITIAL_CONVERSATION_LIST';
export const LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const ADD_CONVERSATION = 'ADD_CONVERSATION';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const LOAD_ERROR = 'LOAD_ERROR';