'use strict';

export const INITIAL_CONVERSATION_LIST = 'INITIAL_CONVERSATION_LIST';
export const LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const ADDING_FRIEND = "ADDING_FRIEND";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const LOAD_ERROR = 'LOAD_ERROR';